### ISSUE TITLE
SAM: Is an additional delay needed for redshifts when calculating GW signals?

### ISSUE THREAD

**Issue by lzkelley** [nanograv/holodeck#53]

**Comment by alexanderbonilla** [comment]
Obviously if you want to have gravitational lens effects in the propagation of the GW's, if this is the effect you are referring to, I have not seen it in stochastic models, only with standard sirens.

**Comment by lzkelley** [comment]
> Obviously if you want to have gravitational lens effects in the propagation of the GW's, if this is the effect you are referring to, I have not seen it in stochastic models, only with standard sirens.

No, sorry, I'm thinking about something different

**Comment by lzkelley** [comment]
Fixed in https://github.com/nanograv/holodeck/commit/e023cecdac54d3f44a448778f6c194be2cdec2ca
