### ISSUE TITLE
Merger and Ringdown stage of the gravitational wave?

### ISSUE THREAD

**Issue by yanyuechuixue** [nanograv/holodeck#93]
I am new to holodeck, so I am sorry if I ask a naive question.

It sames that holodeck.utils.gw_strain_source do not consider the contribution of Merger and Ringdown stage of GW, only the inspiral stage, right?

If so, is there any plan to add the contribution of Merger and Ringdown ?

Thank you very much.

**Comment by lzkelley** [comment]
Hi @yanyuechuixue, you're correct - this function is just the instantaneous GW strain, and it is usually used in a form of the GWB calculation that assumes it's the slow inspiral regime.  This is usually expected to be appropriate for pulsar timing array signals.

We would like to include merger and ringdown waveforms (e.g. for LISA calculations), but there isn't currently anyone working on adding them specifically.  There is a possibility of utilizing an external library like [BOWIE](https://github.com/mikekatz04/BOWIE).

**Comment by yanyuechuixue** [comment]
Thank you very much!
